export const VILLAGE_STATUS: {
  PROLOGUE: string
  ROLLCALLING: string
  PROGRESS: string
  EPILOGUE: string
  COMPLETE: string
  CANCEL: string
} = {
  PROLOGUE: 'PROLOGUE',
  ROLLCALLING: 'ROLLCALLING',
  PROGRESS: 'IN_PROGRESS',
  EPILOGUE: 'EPILOGUE',
  COMPLETE: 'COMPLETED',
  CANCEL: 'CANCEL'
}

export const MESSAGE_TYPE: {
  PUBLIC_SYSTEM: string
  PRIVATE_SYSTEM: string
  PRIVATE_ABILITY: string
  PRIVATE_PSYCHIC: string
  PRIVATE_WEREWOLF: string
  PRIVATE_MASON: string
  PRIVATE_FOX: string
  NORMAL_SAY: string
  MONOLOGUE_SAY: string
  GRAVE_SAY: string
  WEREWOLF_SAY: string
  MASON_SAY: string
  SPECTATE_SAY: string
  CREATOR_SAY: string
  PARTICIPANTS: string
} = {
  PUBLIC_SYSTEM: 'PUBLIC_SYSTEM',
  PRIVATE_SYSTEM: 'PRIVATE_SYSTEM',
  PRIVATE_ABILITY: 'PRIVATE_ABILITY',
  PRIVATE_PSYCHIC: 'PRIVATE_PSYCHIC',
  PRIVATE_WEREWOLF: 'PRIVATE_WEREWOLF',
  PRIVATE_MASON: 'PRIVATE_MASON',
  PRIVATE_FOX: 'PRIVATE_FOX',
  NORMAL_SAY: 'NORMAL_SAY',
  MONOLOGUE_SAY: 'MONOLOGUE_SAY',
  GRAVE_SAY: 'GRAVE_SAY',
  WEREWOLF_SAY: 'WEREWOLF_SAY',
  MASON_SAY: 'MASON_SAY',
  SPECTATE_SAY: 'SPECTATE_SAY',
  CREATOR_SAY: 'CREATOR_SAY',
  PARTICIPANTS: 'PARTICIPANTS'
}

export const NOONNIGHT_CODE: {
  NOON: string
  VOTE_FIRST: string
  VOTE_SECOND: string
  VOTE_THIRD: string
  NIGHT: string
} = {
  NOON: 'NOON',
  VOTE_FIRST: 'VOTE_FIRST',
  VOTE_SECOND: 'VOTE_SECOND',
  VOTE_THIRD: 'VOTE_THIRD',
  NIGHT: 'NIGHT'
}
